name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.2.7
        with:
          report: true
          reuse-go: true
        continue-on-error: true
